export const APP_CONSTANTS = {
  response: {
    ERROR: 'Error',
    SUCCESS: 'Success',
    INVALID_TOKEN: 'Invalid Token',
  },
  USER_ROLE: {
    RETAILER_TYPE: 4,
    DISTRIBUTOR_TYPE: 5,
  },
  NOTIFICATION_TYPE: {
    SUPERSALES_ORDER: 109,
    SUPERTRADE_DISTRIBUTOR_ADD_SALES: 165,
    SUPERTRADE_RETAILER_PURCHASE_RETURN: 166,
    SUPERTRADE_RETAILER_PARTIAL_PURCHASE_REQUEST: 169,
    SUPERTRADE_DISTRIBUTOR_PARTIAL_PURCHASERETUN_REQUEST: 170,
  },
  NOTIFICATION_STATUS: {
    STATUS_PENDING: 1,
    STATUS_APPROVED: 2,
    STATUS_REJECTED: 3,
    STATUS_CANCELLED: 4,
    STATUS_ALERT: 5,
    STATUS_SYNC: 6,
    STATUS_CLOSE: 7,
  },
  NOTIFICATION_SELF: {
    IS_SELF_FALSE: 0,
    IS_SELF_TRUE: 1,
  }
};