export class Product {
    ProductID: number;
    Product_Cat_ID: number;
    Product_Sub_Cat_ID: number;
    ProductCode: string;
    Name: string;
    BarCode: string;
    Price: number;
    ProductAmount: number;
    Quantity: number;
    acceptQty: number;
    originalQty: number;
    ReturnQuantity: number;
    posibleReturnQty: number;
    Discount: number;
    DiscountA: number;
    DiscountB: number;
    DiscountC: number;
    DiscountPresent: number;
    DiscountType: number;
    MaxDiscount: number;
    points: number;
    points_boost: number;
    tot_points: number;
    tot_points_boost: number;
    return_points: number;
    return_points_boost: number;
    SGSTTax: number;
    SGSTSurcharges: number;
    IGSTTax: number;
    IGSTSurcharges: number;
    CGSTTax: number;
    CGSTSurcharges: number;
    VATPercentage: number;
    InclusiveExclusive: number;
    VATFrom: string;
    serial_no: string;
    //SO
    CustomerClass:number;
    expanded:boolean;
    FOCQuantity:number;
    IsPromotional:number;
    subcategories:any;

    clear(): void {
        this.ProductID = 0;
        this.Product_Cat_ID = 0;
        this.Product_Sub_Cat_ID = 0;
        this.ProductCode = '';
        this.Name = '';
        this.BarCode = '';
        this.Price = 0;
        this.ProductAmount = 0;
        this.Quantity = 0;
        this.acceptQty = 0;
        this.originalQty = 0;
        this.ReturnQuantity = 0;
        this.posibleReturnQty = 0;
        this.Discount = 0;
        this.DiscountA = 0;
        this.DiscountB = 0;
        this.DiscountC = 0;
        this.DiscountPresent = 0;
        this.MaxDiscount = 0;
        this.points = 0;
        this.points_boost = 0;
        this.tot_points = 0;
        this.tot_points_boost = 0;
        this.return_points = 0;
        this.return_points_boost= 0;
        this.SGSTTax = 0;
        this.SGSTSurcharges = 0;
        this.IGSTTax = 0;
        this.IGSTSurcharges = 0;
        this.CGSTTax = 0;
        this.CGSTSurcharges = 0;
        this.VATPercentage = 0;
        this.InclusiveExclusive = 0;
        this.VATFrom = '';
        this.serial_no = '';
        this.DiscountType = 0;
        
        //SO
        this.CustomerClass = 0;
        this.expanded = false;
        this.FOCQuantity = 0;
        this.IsPromotional = 0;
        this.subcategories = [];
	}
}