export class Product {
    ProductID: number;
    Product_Cat_ID: number;
    Product_Sub_Cat_ID: number;
    ProductCode: string;
    Name: string;
    BarCode: string;
    Price: number;
    ProductAmount: number;
    Quantity: number;
    acceptQty: number;
    originalQty: number;
    ReturnQuantity: number;
    posibleReturnQty: number;
    Discount: number;
    DiscountA: number;
    DiscountB: number;
    DiscountC: number;
    DiscountPresent: number;
    DiscountType: number;
    MaxDiscount: number;
    points: number;
    points_boost: number;
    tot_points: number;
    tot_points_boost: number;
    SGSTTax: number;
    SGSTSurcharges: number;
    IGSTTax: number;
    IGSTSurcharges: number;
    CGSTTax: number;
    CGSTSurcharges: number;
    VATPercentage: number;
    InclusiveExclusive: number;
    VATFrom: string;
    serial_no: string;

    clear(): void {
        this.ProductID = undefined;
        this.Product_Cat_ID = undefined;
        this.Product_Sub_Cat_ID = undefined;
        this.ProductCode = '';
        this.Name = '';
        this.BarCode = '';
        this.Price = undefined;
        this.ProductAmount = undefined;
        this.Quantity = undefined;
        this.acceptQty = undefined;
        this.originalQty = undefined;
        this.ReturnQuantity = undefined;
        this.posibleReturnQty = undefined;
        this.Discount = undefined;
        this.DiscountA = undefined;
        this.DiscountB = undefined;
        this.DiscountC = undefined;
        this.DiscountPresent = undefined;
        this.MaxDiscount = undefined;
        this.points = undefined;
        this.points_boost = undefined;
        this.tot_points = undefined;
        this.tot_points_boost = undefined;
        this.SGSTTax = undefined;
        this.SGSTSurcharges = undefined;
        this.IGSTTax = undefined;
        this.IGSTSurcharges = undefined;
        this.CGSTTax = undefined;
        this.CGSTSurcharges = undefined;
        this.VATPercentage = undefined;
        this.InclusiveExclusive = undefined;
        this.VATFrom = '';
        this.serial_no = '';
	}
}